### ISSUE TITLE
While playing South at around the final part, there's notes and I don't hear me singing!

### ISSUE THREAD

**Issue by nerfandgetfit** [FunkinCrew/Funkin#115]
It's not out of sync it's just this part. It's on normal mode and it happens at around 1 minute or 50 seconds in.

**Comment by Squirrel-God** [comment]
They made a little mistake with the charting. In the debug menu, you can see this box that says "Must hit section". To put it simply, if that box is checked then that means that it is the player's turn to press notes. Since the spooky pair are still singing, that box shouldn't be checked, but it is and that's why the problem arises.
