### ISSUE TITLE
I have a Question: 

### ISSUE THREAD

**Issue by YousefTamer67** [FunkinCrew/Funkin#1310]
i was trying to compile the game but there was an error

#1306 
![Screenshot (139)](https://user-images.githubusercontent.com/82932252/123515716-db723480-d698-11eb-8a9a-b713c2e4c15c.png)

**Comment by FacuXito** [comment]
I recommend you re-install the funkin mod and put the Project.xml file in your mod and if you keep getting the same error inside the assest folder create the preload folder and then create the export folder in release in windows and finally bin, Although I recommend that you copy the latter from the original game so that you do not fail, I hope I have helped you friend!

**Comment by YousefTamer67** [comment]
i was making a mod

**Comment by YousefTamer67** [comment]
![duck_assets](https://user-images.githubusercontent.com/82932252/123550861-bb617480-d76f-11eb-9349-0e5b4bb5d8f7.png)

**Comment by FacuXit0I** [comment]
And what is that?

**Comment by YousefTamer67** [comment]
Duck

**Comment by ACardboardBox1** [comment]
> 
> 
> ![duck_assets](https://user-images.githubusercontent.com/82932252/123550861-bb617480-d76f-11eb-9349-0e5b4bb5d8f7.png)

it's definitely something

**Comment by nickpythonluajava** [comment]
> > 
> 
> > 
> 
> > ![duck_assets](https://user-images.githubusercontent.com/82932252/123550861-bb617480-d76f-11eb-9349-0e5b4bb5d8f7.png)
> 
> 
> 
> it's definitely something

It says "duck_assets" so it might be modded

**Comment by YousefTamer67** [comment]
wait i should need someone else to compile

**Comment by ninjamuffin99** [comment]
fnf mod cant help
