### ISSUE TITLE
Pretty obvious input lag

### ISSUE THREAD

**Issue by Trogtor** [FunkinCrew/Funkin#165]
I'm surprised there hasn't been a thread on this yet, but there is some pretty obvious input lag. I'll hit notes on-par with the beat of the song and i'll only get 'GOOD' or 'SHIT' hits, sometimes it doesn't hit at all. This makes it really hard to play some of the harder songs. You can even check for yourself by listening to the audio queues when you navigate the main menu to the beat of the background music.

**Comment by Farpie** [comment]
I'm also very surprised, as this is an issue I noticed pretty much immediately. Most of the notes feel consistently ahead of the song, and some are just flat out not on the beat they represent. It's never made me out right fail a song, but a setting to adjust the visual/audio latency would be fantastic

**Comment by Trogtor** [comment]
A latency adjustor would be nice, but it would only be a temporary since the game itself already has latency issues.

**Comment by gedehari** [comment]
I noticed it too but on HTML5 builds of the game, the Desktop platforms feels kinda fine to me

**Comment by MCRusher** [comment]
I felt this too, but just assumed the timing was different from the games I'm used to.

**Comment by DJSterf** [comment]
Would there be interest in note fixes and sync adjustments to the actual game?  I made a pretty rudimentary tool to resync charts and adjust Global Offset (i.e. net audio vs. display lag).  So far, I've resynced the Hard charts for Pico, South, and Cocoa so far and get Full Sick Combos on those just about any time the game doesn't lag.  South had a lot of wrongly quantized notes, but the note intents were fairly easy to figure out.  Cocoa was great -- no notes were wrong, so that one was just an offset adjustment for my headphones (125 milliseconds between Song Offset and Global Offset additions, though, ouch).

Two key additions to the code would be: (1) Adding a Song Offset in the Stepchart Editor, and then adjust the note blocks in the editor with that offset, and (2) Adding in a setting somewhere for Global Offset and then using that in calculating step placement during the actual song.  Maybe a Settings Menu with that as well as the Volume Level and Fullscreen Toggle?  There are what, 14 visible songs right now?  3 charts each...maybe kind of rough to do unless there's a lot of demand for it.  But if I finish resyncing all the Hard charts eventually, I'd want them to be consistent (i.e. don't want some early, some late), so I'd do some heavy testing on that before I make a mod of it or submit to the git at all.  Anyway, lemme know thoughts/etc.

**Comment by Farpie** [comment]
This would be very much appreciated! I also noticed the wrongly quantized notes, but I figured that would be fixed when the latency was addressed. Still, having a rough patch now would personally give me much more of a reason to come back and replay the current charts

**Comment by DJSterf** [comment]
What's the normal M.O. for that type of change request here?  (Just started playing maybe 6 days ago)  Message someone?  Post somewhere (or a new thread here)?

**Comment by ninjamuffin99** [comment]
I been keepin an eye on things. Thinkin of an elegant and nice way to go about fine tuning all the charts and all that and seeing what others are doin.

**Comment by DJSterf** [comment]
Cool -- I think it'd be a really good time investment to get those really sharp and allow for per-machine latency adjustments.  I've had a ton of fun playing the few fixed and synced charts that I've gotten to so far, and I guess making the adjustment tool and eyeballing audio offsets in Audacity has been kind of like a fun puzzle, lol.  If you need any feedback on implementation, lemme know.  I think I covered most of the high-level suggestions above.

**Comment by ninjamuffin99** [comment]
I've seen your vid where you rechart Pico and it very interestin!
The dream is to be able to see the waveform of the audio from within the chart editor, so from IN the chart editor itd be possible to line it up as accurately as possible.

**Comment by DJSterf** [comment]
haha cool, yeah I've added a few more features that helped me w/ South's 165 bpm math (namely first note millisecond value and BPM, which allow 'snap/recalculate to nearest 16th' to fix any slightly-off steps).  The waveform would be a solid addition.  Any plans on a Stepchart preview with some sort of tick or handclap sound (e.g. play current or multiple Measures in the Stepchart Editor with options for background audio, voice overlay audio, and a handclap)?  Might help w/ sync identification (though again, each machine is going to have unique audio lag discrepancies, so still definitely recommending a separate Global Offset on top of what's done in the Stepchart Editor).

**Comment by DJSterf** [comment]
Updating, too -- I fixed up the player's chart to Winter-Horrorland/resynced it to get a Full Sick Combo, and the notes are pretty tight with the song now.  I touched up one of Lemon's notes, but not more than that.  I'll get a video with WH and Eggnog, probably Friday.  I might move a few notes in Eggnog if I get some time this weekend.  Let me know if you want these adjusted files (though note that sync-wise, they'd likely have to be globally adjusted if your setup is earlier or later than mine).  B-)

**Comment by DJSterf** [comment]
I made an Global Offset Adjustment Tool for FNF and resynced 8 of the charts.  Spookeez has a bit of song drift, and same w/ Winter Horrorland at the last quarter...but the rest are pretty nice now.  Here's the .zip file with the Global Offset Adjustment Tool and 8 of the songs so far.  Slight fixes to charts where the quantization was incorrect, and Spookeez was very highly redone.
[FNFZeroOffsetAndGlobalOffsetAdjustmentTool.zip](https://github.com/ninjamuffin99/Funkin/files/5963223/FNFZeroOffsetAndGlobalOffsetAdjustmentTool.zip)
Let me know if there's interest in me doing the rest of these whenever I get more time these next few weeks.

**Comment by DJSterf** [comment]
(and for reference, my Global Offset w/ this is 89 ms)
