### ISSUE TITLE
Bug Report: [The options menu wont work and the games telling me that my game is outdated even though it isnt]

### ISSUE THREAD

**Issue by AcePlayzGamesYT** [FunkinCrew/Funkin#1888]
So my options menu wont work and the games telling me that my game is outdated even though it isnt
https://user-images.githubusercontent.com/94937764/143272045-eea14881-0488-4753-980e-9c21f7a97e5e.mp4
https://user-images.githubusercontent.com/94937764/143272645-9326161c-2bff-42a7-8d6e-a862fc301384.mp4

**Comment by ACrazyTown** [comment]
The Options Menu is broken in the current source code and only shows up when compiled with debug (i think)
as for the outdated version, i believe it has something to do with the fact that there's a newer version on NG (week7)

**Comment by AcePlayzGamesYT** [comment]
how do you compile with debug?

**Comment by AcePlayzGamesYT** [comment]
nvm i figured it out but the options menu still wont work

**Comment by ACrazyTown** [comment]
> nvm i figured it out but the options menu still wont work

like i said, the options menu is broken in the current source code

**Comment by AbnormalPoof** [comment]
The outdated error is due to the game having no entrypoint to check the Newgrounds version, this is due to the game using the `NGio.GAME_VER_NUMS` string instead of the intended `NGio.GAME_VER` string.

Another reason for the update error is due to the game unable to check the version since there is no API key specified.
