### ISSUE TITLE
compiling help

### ISSUE THREAD

**Issue by ANDYYYYYYYYXD** [FunkinCrew/Funkin#1955]
whenever i compile the game this shows up

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/fs/PolymodFileSystem.hx:18: characters 18-20 : Expected )

**Comment by Deltara3** [comment]
I had this same exact issue, despite the README saying to use Haxe 4.1.5, I just used the latest and it compiled.

However, there seem to be issues and I'm not sure if its because of the newer version.

Issues I've seen includes:
- Crashing when entering Freeplay
- Third song in each week not showing up in the Story Menu. (Might be only visual)

My best guess is that Polymod updated and its now incompatible with Haxe 4.1.5.

**Comment by marius851000** [comment]
There is a fix for freeplay : https://github.com/ninjamuffin99/Funkin/pull/412
And I think the third song not appearing is actually to prevent spoiler based on the name of the last song.

**Comment by ACrazyTown** [comment]
third song not appearing is just a bug with openfl i believe
install openfl using git and it should work

**Comment by byemc** [comment]
> My best guess is that Polymod updated and its now incompatible with Haxe 4.1.5.

It updated with bad syntax and broke itself, though after applying a change manually (I’ve [opened a PR](https://github.com/larsiusprime/polymod/pull/114) on their repo about three weeks ago now) the issues with Freeplay and Story are still there.
