### ISSUE TITLE
Create an option that allows you to have the voice of BF, GF and the Opponent separately. Example: Voices_BF.ogg, Voices_GF.ogg, Voices_OP.ogg

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [FunkinCrew/Funkin#2049]
Having an option that allows the game to have the BF's voice separate from the opponent's would make it easier to chart songs, and if there is a moment in the song where GF sings then that's separate as well.

I don't know if it's a good idea

**Comment by Paidyy** [comment]
bf's and op's voice tracks will be added to the game

**Comment by lordp78ng** [comment]
100% good idea, should be added.

**Comment by MemeHoovy** [comment]
this has what your looking for https://github.com/MemeHoovy/FNF-PsychEngine-Extra-1

**Comment by Swapper1** [comment]
For GF's and opponent's voice tracks, I would like to see how [GF crying instead of cheering in Tutorial if the player misses the note](https://github.com/KadeDev/Kade-Engine/blob/stable/source/PlayState.hx#L4495). But speaking of GF's vocal track...what if GF use opponent's and/or GF's voice at the same time?

**Comment by HackersLOLwskasdhq3ew** [comment]
There isnt a Voices.ogg file for the tutorial song
