### ISSUE TITLE
Enhancement: Update Funkin repo to most recent version

### ISSUE THREAD

**Issue by muivatcO** [FunkinCrew/Funkin#2248]
## What is your suggestion, and why should it be implemented?
My suggestion is that the Funkin repo should be updated to the newer released version.

**Comment by CrusherNotDrip** [comment]
Nah, they should just get a USB, put it on a USB, and throw it away in a fire. After that happens, no one will ever have the source code for years to come. UNTIL... Someone will time travel to stop the USB from burning, and that someone will become a hero until he trips and dies on a Lego brick left on the floor by his 5-year-old kid. It's ok though, as someone will time travel again to stop him, but unfortunately, it turns out he's a super villain trying to take over the world, and he almost succeeded in doing so until boyfriend came out of the USB and beat him in a rap battle. Boyfriend saves the universe, and the Friday Night Funkin' universe is now canon to Mother Earth as we know it.

**Comment by CharlesCatYT** [comment]
> ## What is your suggestion, and why should it be implemented?
> My suggestion is that the Funkin repo should be updated to the newer released version.

when the last 0.3.x version releases maybe

**Comment by TheoDevelops** [comment]
> > ## What is your suggestion, and why should it be implemented?
> > My suggestion is that the Funkin repo should be updated to the newer released version.
> 
> nah they'll do it when the last 0.3.x version releases maybe
> 

elite master eric alr said that the source code will release very soon

**Comment by Maritsu** [comment]
wasn't the game supposed to be open-source? and were there any actual updates to the NG release since week 7 dropped a few years ago?

**Comment by TechnikTil** [comment]
> Nah, they should just get a USB, put it on a USB, and throw it away in a fire. After that happens, no one will ever have the source code for years to come. UNTIL... Someone will time travel to stop the USB from burning, and that someone will become a hero until he trips and dies on a Lego brick left on the floor by his 5-year-old kid. It's ok though, as someone will time travel again to stop him, but unfortunately, it turns out he's a super villain trying to take over the world, and he almost succeeded in doing so until boyfriend came out of the USB and beat him in a rap battle. Boyfriend saves the universe, and the Friday Night Funkin' universe is now canon to Mother Earth as we know it.

Boyfriend is Ness???

**Comment by fluoriteByte** [comment]
> > Nah, they should just get a USB, put it on a USB, and throw it away in a fire. After that happens, no one will ever have the source code for years to come. UNTIL... Someone will time travel to stop the USB from burning, and that someone will become a hero until he trips and dies on a Lego brick left on the floor by his 5-year-old kid. It's ok though, as someone will time travel again to stop him, but unfortunately, it turns out he's a super villain trying to take over the world, and he almost succeeded in doing so until boyfriend came out of the USB and beat him in a rap battle. Boyfriend saves the universe, and the Friday Night Funkin' universe is now canon to Mother Earth as we know it.
> 
> Boyfriend is Ness???

HE'S SANS????
