### ISSUE TITLE
HELP!! "Unexpected ?"

### ISSUE THREAD

**Issue by HertzLUK** [FunkinCrew/Funkin#2327]
When I type lime test windows -debug this appears: source/funkin/Paths.hx:116: characters 75-76 : Unexpected ?

**Comment by moxie-coder** [comment]
you need haxe 4.3

**Comment by HertzLUK** [comment]
It worked but now this appears: source/funkin/audio/visualize/ABotVis.hx:11: characters 8-39 : Type not found : funkin.vis.dsp.SpectralAnalyzer

**Comment by METGameDev** [comment]
thats because its not finding the funkin.vis and cant locate it. try downloading the contents of https://github.com/FunkinCrew/funkVis and placing it into here like so:
![image](https://github.com/FunkinCrew/Funkin/assets/76184245/05e816de-da96-49da-a48a-3a4632f21d06)

I think theres an oversight with how funkin.vis is named, considering theres a dot in there and haxe usually uses the dots to call bits of the library, so instead of importing "funkin.vis", its trying to import "funkin" and call the "vis" part of it. Just a theory though.

**Comment by HertzLUK** [comment]
It worked and now I get this error: source/funkin/modding/PolymodHandler.hx:294: characters 7-24

**Comment by METGameDev** [comment]
getting that error too, trying to figure it out now.

**Comment by ziopero11** [comment]
when i type lime test windows -debug, it says: C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/animate/FlxAnim.hx:26: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/funkin/api/newgrounds/NGio.hx:6: characters 8-24 : Type not found : io.newgrounds.NG
