### ISSUE TITLE
polymod isue

### ISSUE THREAD

**Issue by cass3000** [FunkinCrew/Funkin#2419]
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

when i compile it gives me this error:
 source/funkin/modding/PolymodHandler.hx:289: lines 289-295 : { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

**Comment by NewEater12k** [comment]
i comment out line 294 and it gives me this error
source/funkin/modding/PolymodHandler.hx:125: lines 125-154 : { useScriptedClasses : Null<Bool>, parseRules : polymod.format.ParseRules, modRoot : String, loadScriptsAsync : Bool, ignoredFiles : Array<String>,... has extra field loadScriptsAsync
source/funkin/modding/PolymodHandler.hx:125: lines 125-154 : ... For function argument 'params'

**Comment by 3zoosE** [comment]
i had an error like this too, even EliteMasterEric knows about this error, he said this happens because you installed an older version of polymod, just try to redo the all installation steps, but don't download the zip file from the website, if you do this error can happen again, just open the prompt in the directory you want, and enter all the installation commands.

**Comment by NewEater12k** [comment]
i installed polymod yesterday via git
is there like a more modern version somewhere?

**Comment by NotHyper-474** [comment]
I had this issue too when trying to build for Linux, for some reason running `hmm reinstall --force polymod` solved it for me
