### ISSUE TITLE
Issue opening the game

### ISSUE THREAD

**Issue by Xervation** [FunkinCrew/Funkin#248]
I downloaded and opened the game and I keep getting this error can someone help me?

https://user-images.githubusercontent.com/77809175/105413514-d1389f80-5bfb-11eb-8424-1e11be2ebec4.mp4

**Comment by yxkimxrax** [comment]
I've gotten this error too, and it was because when you open the game using the taskbar or searching it up, it does not ask for the other important files that come with the game. When it notices it can't get to these files (the music, assets, etc.) it will throw up that exact error. If possible, I wouldn't open it using that way, I'd put the entire folder (with the exe, and all the files needed to run) on your desktop/taskbar, instead of just the exe.

**Comment by regulad** [comment]
> 
> 
> I've gotten this error too, and it was because when you open the game using the taskbar or searching it up, it does not ask for the other important files that come with the game. When it notices it can't get to these files (the music, assets, etc.) it will throw up that exact error. If possible, I wouldn't open it using that way, I'd put the entire folder (with the exe, and all the files needed to run) on your desktop/taskbar, instead of just the exe.

or, yknow, you can just use a shortcut, they work wonders
