### ISSUE TITLE
Bug Report: game freezes when you beat a song with no notes in it

### ISSUE THREAD

**Issue by Willio2000** [FunkinCrew/Funkin#2810]
## Describe the bug
if you beat a song that has no notes in it, the game doesn't know how to calculate how much percentage you got, and freezes.

## To Reproduce
remove all the notes in a song

## Expected behavior
don't freeze and say 0% accuracy

## Screenshots/Video
![what happened](https://github.com/FunkinCrew/Funkin/assets/65547044/deba8c30-efc8-4306-a00b-1b50fa2fa833)

## Desktop
 - OS:
windows 10
 - Browser
chrome
 - Version:
0.4.1

## Additional context
this is pretty straightforward i think so yeah

**Comment by Hundrec** [comment]
Fortunately, there's no way to make this happen without purposefully importing an empty chart file.

Replicated the bug on Windows 11. The game freezes, says "Not Responding", then requires a force close.

https://github.com/FunkinCrew/Funkin/assets/170126004/5c0d16e5-f698-45f5-8d24-1d0b021d5d61

**Comment by EliteMasterEric** [comment]
Confirmed, reproduced in-game with the provided steps.

The issue is that the game calculates the clear percent as `(Sick Notes Hit + Good Notes Hit) / Total Notes`, rounded down. If total notes is 0, the clear percent is `NaN`, an invalid number. Attempting to round down `NaN` results in `-2,147,483,648`, and the counter tries to display that number, resulting in unintended behavior.

**Comment by NotHyper-474** [comment]
Mmm, division by zero error my beloved
