### ISSUE TITLE
Bug Report: Held notes don't register if tapped. [hard to fix]

### ISSUE THREAD

**Issue by Beelijah** [FunkinCrew/Funkin#2909]
## Describe the bug
If you play any song with a hold note and you tap the hold note, it acts as a regular note.

## To Reproduce
Don't hold down hold notes.
## Expected behavior
The rest of the hold note should come by, and deal damage for missing it.

## Screenshots/Video
[this is not on youtube](https://www.youtube.com/watch?v=rq3Fy47qj0Y)

## Desktop
 - OS: Windows 11
 
 - Browser: Edge (also works on executable)
 
 - Version: 0.3.2 --> latest

## Additional context
none

**Comment by Hundrec** [comment]
I believe this is an intentional gameplay change.

Hold note trails are now coded to give you a lot of points when held down, so the game heavily incentivizes you to hold them down. 
This system feels less punishing than the old one, because I'd often miss a single trail because I couldn't tell exactly when to release. 

If the devs want to, they could easily re-implement the Legacy and Week 7 input systems in Preferences.hx!
The code is available to view  [here](https://github.com/FunkinCrew/Funkin/blob/9bd09e37915300ca595950a6dcc2b215f7dcf077/source/funkin/play/scoring/Scoring.hx)

**Comment by Beelijah** [comment]
Okay!
