### ISSUE TITLE
Enhancement: Add a Daddy Dearest and Week 5 Parents Loss Icon

### ISSUE THREAD

**Issue by CoolDudeT** [FunkinCrew/Funkin#3048]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

This seems pretty obvious, but Daddy Dearest and the Parents in Week 5 don't have a losing icon on their health icon.
Maybe you can do something like the images included. (If you do end up using it, credit KadeDev as he made it, at least I think so.)
Thanks Funkin Crew! (BTW, love the new update.)
![icon-dad](https://github.com/user-attachments/assets/d77643a7-0417-459c-8d10-9f5e186a3b9a)
![icon-parents](https://github.com/user-attachments/assets/3c75ffcc-a04e-4e2d-84eb-c28a7da20808)

**Comment by EliteMasterEric** [comment]
Not currently planned, and even if it was we wouldn't use other people's art for it.

**Comment by TJHOnGithub** [comment]
actually, i believe either an early dd icon or the final one DOES have an official danger sprite, that being the one from the ludum dare prototype, its only in the files though, i think its in some concept art for the character select menu along with mommy mearest so it IS finished and is somewhere, seemingly evilsk8rs pc or whatever they use since the concept arts all in their style

**Comment by JamJarIsDumb** [comment]
Found a clip of PA saying he was going to get this implemented? Is this still not planned?
Source: https://www.youtube.com/watch?v=J0aEx_z_QEY&t=17519s at 35:33

**Comment by AbnormalPoof** [comment]
Side note: There is a losing icon used in one of the concept images for the character select:
![Screenshot 2024-10-27 at 10 23 04 AM](https://github.com/user-attachments/assets/6051cd8f-e5be-474f-9c66-66aa0a46a14b)
I'm pretty sure this is the Kade Engine icon though.

**Comment by JamJarIsDumb** [comment]
> Side note: There is a losing icon used in one of the concept images for the character select: ![Screenshot 2024-10-27 at 10 23 04 AM](https://github.com/user-attachments/assets/6051cd8f-e5be-474f-9c66-66aa0a46a14b) I'm pretty sure this is the Kade Engine icon though.

DDs losing icon has been around since early builds, until the graffix file was removed. It was just never used for some reason.
Shown at 1:50, the icon in the character select concept art uses this same icon. I believe there has been confusion around it as it was used in KadeEngine, however it did not originate from there.

https://www.youtube.com/watch?v=rROesndykws&t=18s

**Comment by Ronin546** [comment]
Will there be a losing icon for Girlfriend?

**Comment by Trofem** [comment]
> Will there be a losing icon for Girlfriend?

I think there is same logic as her parents.
And also, i think losing icon in tutorial would be strange

**Comment by charlesisfeline** [comment]
> Will there be a losing icon for Girlfriend?

like dad like daughter
