### ISSUE TITLE
Bug Report: Most sprites replaced by black boxes.

### ISSUE THREAD

**Issue by flame-controller** [FunkinCrew/Funkin#370]
Playing off itch.io

v0.2.7

Windows 10 OS

https://user-images.githubusercontent.com/67610383/107123869-23212c80-686e-11eb-8efb-9d703ee4d61c.mp4

week 2 is the worst.
week 4 is best.

https://user-images.githubusercontent.com/67610383/107123892-506dda80-686e-11eb-9c6b-5393c46a0e86.mp4

Only week 6 is unaffected
week select also affected

https://user-images.githubusercontent.com/67610383/107123927-7abf9800-686e-11eb-8e75-e338a479a270.mp4

tell me if you need more info.
still playable, the arrows work.

**Comment by Midou36O** [comment]
Can confirm, but in my case this happens because of my GPU, switching drivers fixes that but the game's FPS drops to 3 which is unplayable.

Missing press to start text + GF missing:
![image](https://user-images.githubusercontent.com/45198486/107144030-aad36d80-6938-11eb-999a-e30d1edb893c.png)

Black Squares instead of characters: 
![image](https://user-images.githubusercontent.com/45198486/107144046-c3438800-6938-11eb-96cd-3e9b988f679f.png)

Tutorial doesn't show anything except the arrows and the health bar:
![image](https://user-images.githubusercontent.com/45198486/107144076-f4bc5380-6938-11eb-9ffc-220016196f61.png)

Week 6 is the only playable part (w/o background sprites):
![image](https://user-images.githubusercontent.com/45198486/107144101-233a2e80-6939-11eb-9ab6-0a172f4cd2f4.png)

For some reason this only happens on windows, on linux i get all the sprites, but the game's loading is really slow (not a bug probably just my pc) but all sprites are rendered correctly.

**Comment by Fancy2209** [comment]
https://github.com/ninjamuffin99/Funkin/issues/356
Same issue :/
The big problem is that I need to find the specific difficulty on the week that doesn't crash the game

**Comment by Fancy2209** [comment]
I know a fix but it isnt reccomend
Replace bf and gf xml and pngs by the one on the ludum dare prototype

**Comment by flame-controller** [comment]
The prototype is missing the same files that the regular one is missing.

**Comment by flame-controller** [comment]
the xml files
