### ISSUE TITLE
Enhancement: Pico-speakers for playable pico

### ISSUE THREAD

**Issue by Szymonkruk12** [FunkinCrew/Funkin#3818]
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

Please fix that because when the player is pico-speakers pico-speakers is playable when playing as boyfriend
![NO](https://github.com/user-attachments/assets/4606e1d1-aa04-4bc2-8805-e6050808d469)
![fIX](https://github.com/user-attachments/assets/42d7660c-9b8d-4100-9710-ac3c609aa75a)
[pico.json](https://github.com/user-attachments/files/17601786/pico.json)

**Comment by AbnormalPoof** [comment]
`pico-speaker` is not included in the list of owned character IDs because you never play as him. 

If you *need* him in the owned character IDs array, you can make a mod which has a JSON patch for Pico's playable character data, or just a mod which replaces the file entirely.

**Comment by EliteMasterEric** [comment]
`pico-speaker` doesn't make sense to have in the list of owned characters by default because he doesn't have sing or miss animations.

If you have modified the `pico-speaker` character to include singing animations, then you can make a JSON patch to `pico.json` file (see the modding documentation for more info on how to do this).
