### ISSUE TITLE
Crash Report: Character Select problem

### ISSUE THREAD

**Issue by KinginNG** [FunkinCrew/Funkin#3895]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.2

### Description

https://github.com/user-attachments/assets/50a3122e-5e36-40d6-9252-fe540b420d09

### Steps to Reproduce

1. Open FNF
2. Go to Freeplay
3. Go inside CS
4. Slide to the new character
5. Crash

### Crash logs

[crash-2024-11-26-06-06-32.log](https://github.com/user-attachments/files/17918369/crash-2024-11-26-06-06-32.log)

**Comment by Hundrec** [comment]
The lock is missing. Did you modify any files?
If you're attempting to mod in a new character, something must've gone wrong.

**Comment by KoloInDaCrib** [comment]
Cannot reproduce. Also as Hundrec pointed the lock is missing, which normally doesn't happen without modifying the files.

I took a gander at the line causing the crash and it seems like the missing lock doesn't have any animations (I mean duh) so when retrieving the name of the current animation playing it causes a crash. This wasn't accounted for during programming of the menu because the crash doesn't happen without modifying the files in one way or another

**Comment by Keoiki** [comment]
I think you guys didn't read the code carefully enough, line 1028 is within the switch block for handling the pixel icons for the characters, not the locks. The crash happens because you either:
1. Do not have an image for the pixel icon
2. You do but it lacks an animation called "idle" in its .xml file

**Comment by KinginNG** [comment]
But the other icon like bf's json also doesn't have anything that says idle

**Comment by Keoiki** [comment]
> But the other icon like bf's json also doesn't have anything that says idle

Yes it does?
![image](https://github.com/user-attachments/assets/f6af5af8-bb06-4c3e-b1cb-6fc7587e82aa)
Also **json**? I specifically said a **xml** file. The pixel icons are separate ones located in `images/freeplay/icons/`, you might've been thinking of the health icons used in songs.

**Comment by KinginNG** [comment]
ok so I figured out that it was the freeplay icon, now I'm having trouble exporting it
