### ISSUE TITLE
Crash Report: Polymod Script Exception when reseting Weekend 1 songs

### ISSUE THREAD

**Issue by AnidogOG** [FunkinCrew/Funkin#3940]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description

whenever i restart any of the weekend 1 songs it gives me a "Polymod Script Exception" and then gives me a "RangeError"
this has never happened before so im not sure why it's happening now
![bandicam 2024-12-16 10-47-32-883](https://github.com/user-attachments/assets/48f2f488-07d0-4f62-8626-febd87347e7a)
![bandicam 2024-12-16 10-47-41-882](https://github.com/user-attachments/assets/2083d540-d8c2-4bde-be11-ae4b9afb265f)

### Steps to Reproduce

1. go to any weekend 1 song in pico freeplay menu
2. enter any weekend 1 song
3. pause the song then restart it

### Crash logs

[crash-2024-12-16-10-47-39.log](https://github.com/user-attachments/files/18155129/crash-2024-12-16-10-47-39.log)

**Comment by KoloInDaCrib** [comment]
Already reported in #3499 

Please close the issue and refer to the discussion in that thread, as duplicate issues can easily clutter the issues tab and hinder visibility of the previously unreported issues!

Side note: I feel like it would be quite useful if an "issue" with commonly reported issues would be pinned so that it's easier for others to see if an issue has been previously reported, since apparently searching it up is too much to ask for
