### ISSUE TITLE
Bug report: Execution error: command "..." failed with status: 1 in cwd

### ISSUE THREAD

**Issue by nr-ncam** [FunkinCrew/Funkin#3952]
### Issue Checklist

- [x] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

Upon attempting to install the needed dependencies through hmm, gives me following error:
![Image](https://github.com/user-attachments/assets/1babe713-b5bb-4b6f-8dd4-0d08723cb33d)
From what I've seen, this can occur on mostly any of the dependencies listed in hmm.json

Does anyone know what could cause this and how to fix this? 
Thanks

**Comment by nr-ncam** [comment]
The reason as to why I'm reinstalling in the first place is the red error in the screenshot
![Image](https://github.com/user-attachments/assets/ebb350b3-26ea-41af-a43f-8a3f9260fc38)

**Comment by NotHyper-474** [comment]
If I'm not mistaken that error could be from either running out of disk space or issues with internet connection.
For disk space there's not much to do other than cleaning for more space, for internet I don't know, maybe you could try running without the `-f` flag so that it only re-installs the other packages if needed.

**Comment by nr-ncam** [comment]
Ok so what worked for me was:
-Clone the DEVELOP branch using Github Desktop
-Repeatedly doing the ```hmm reinstall -f``` command until it worked
It's compiling rn
Gonna close this
