### ISSUE TITLE
Bug Report: Sustain notes sometimes randomly miss

### ISSUE THREAD

**Issue by NickHam13** [FunkinCrew/Funkin#424]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (64-bit)

## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7.1

## Please describe your issue. Provide extensive detail and images if possible.

Title pretty much says it all. Sustain notes feel very inconsistent in the new version. I sometimes miss them even when it feels like my inputs are correct. Definitely related to the new update, I was playing 0.2.7 earlier today and everything felt fine. Probably just a mistake from the sustain note overhaul in commit 2479eaa5db296ad1bc0944084ca2c86bb3f085fd.

**Comment by PrincessMtH** [comment]
[This](https://github.com/ninjamuffin99/Funkin/blob/master/source/PlayState.hx#L1566) is the only place I can imagine it messing up, if there's somehow a chance a sustain note can be hit without wasGoodHit being flagged or if my oversight (see below) has any impact? Will have to look into this. The main intended changes to sustain note behaviour in my commit were:

### Note.hx
- [Sustain note segment scaling fix](https://github.com/ninjamuffin99/Funkin/commit/2479eaa5db296ad1bc0944084ca2c86bb3f085fd#diff-c8e2cdd76fe709cbf7f47753aeefe36b184c8ce77849be19865669e4ef6100cfR161) (now calls updateHitbox instead of manually setting the offset)
### PlayState.hx
- [Apply a clipRect to notes as they're being held](https://github.com/ninjamuffin99/Funkin/commit/2479eaa5db296ad1bc0944084ca2c86bb3f085fd#diff-662f3951244e5a18b1b71ae63b39e79de701bd1008090b8afa24ad96a31161bcR1504), SHOULD be purely a visual change
- _[Don't kill sustain notes after being hit](https://github.com/ninjamuffin99/Funkin/commit/2479eaa5db296ad1bc0944084ca2c86bb3f085fd#diff-662f3951244e5a18b1b71ae63b39e79de701bd1008090b8afa24ad96a31161bcR2126) so they can still be drawn_
- _[Don't deduct health or mute the voices if a correctly hit sustain note reaches the top of the screen](https://github.com/ninjamuffin99/Funkin/commit/2479eaa5db296ad1bc0944084ca2c86bb3f085fd#diff-662f3951244e5a18b1b71ae63b39e79de701bd1008090b8afa24ad96a31161bcR1558), this is of course paired with the other change of not removing them on hit._

The only oversight I know I made is that sustain notes now aren't set to be inactive and invisible, but they are still being killed, removed, and destroyed. If that ends up being the culprit, I propose the function simply be changed to remove the honestly unnecessary first if statement, making it:
```haxe
if (daNote.y < -daNote.height)
{
	if (daNote.tooLate || !daNote.wasGoodHit)
	{
		health -= 0.0475;
		vocals.volume = 0;
	}

	daNote.active = false;
	daNote.visible = false;

	daNote.kill();
	notes.remove(daNote, true);
	daNote.destroy();
}
```
I've not been actually run into the issue myself however, so I'd appreciate any help from other contributors in trying to figure it out. Thanks!

**Comment by PrincessMtH** [comment]
Looked into it a bit more, it seems like badNoteCheck() is being called when it shouldn't be. Adding an extra check in noteCheck like so:
```haxe
function noteCheck(keyP:Bool, note:Note):Void
{
	if (keyP)
		goodNoteHit(note);
	else
	{
		if (!(note.isSustainNote && note.wasGoodHit))
			badNoteCheck();
	}
}
```
alleviates those issues, but sustain notes will still randomly miss, so that's not all that's going on. Will edit/submit a PR once I figure out what.
