### ISSUE TITLE
Bug Report: It keeps stopping at a certain loaded amount

### ISSUE THREAD

**Issue by DDReeGDr** [FunkinCrew/Funkin#439]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by DDReeGDr** [comment]
using chrome, used newgrounds (issue is in newgrounds)

**Comment by Bloatatoe** [comment]
download the desktop version, I had the same issue and multiple bug when playing on chrome. Its because of my laptop having 2 graphic cards and the integrated one is very weak compared to the other. Weak pc seems to have a lot of issue with this game (most games actually). I never encountered a bug since I downloaded the desktop version. I played this game for about 20+ hours. (yes im addicted to this game)
