### ISSUE TITLE
Bug Report: M.I.L.F Charting Errors

### ISSUE THREAD

**Issue by superguyoffa** [FunkinCrew/Funkin#522]
You can see it in this [YouTube video](https://youtu.be/rH24gi1TQys?t=79) (timestamp included)

Near around 1:22 Boyfriend has the Mom's notes and Mom has the Boyfriend's notes. It's switched up.

**Comment by Helper006** [comment]
It is more apparent if you continue watching from that timestamp for about 6 seconds.

**Comment by justamole** [comment]
yeah its been pretty annoying but in high that switch is a life saver
![hard](https://user-images.githubusercontent.com/79595919/110140652-ee839080-7d99-11eb-8efe-2016c6153122.png)

**Comment by ActualMandM** [comment]
I talked about this in another server and noted how the camera doesn't even switch over to the Boyfriend when these notes hit

https://youtu.be/iFCAHNquhus?t=335

Toggling Must Hit Section for these sections fixes the issue entirely

It's possible that since the icons signifying who's playing which side weren't implemented at the time, whoever was charting the song got confused and thought it was enabled when in reality it wasn't

**Comment by lolBoi9696** [comment]
Or this could be intended lol
