### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by donutmp3** [FunkinCrew/Funkin#645]
The game has A LOT of lag spikes. This could just be the engine the game is running on, but it gets really annoying whenever you want to 100% a song. Maybe attempt fixing the engine?

**Comment by TentaRJ** [comment]
## Woah buddy! This issue doesn't have a proper description! Please use the template next time you create your issue!

**Comment by Rudxain** [comment]
I agree with the template comment. But I want to say that I have a similar problem. I get lag spikes regardless of the week, and they are unpredictable.

Specs:
- Using installable (compiled) FNF.
- Windows 10 x64 (x86 / AMD64)
- CPU 64bit Intel core i5 (I don't remember what generation, but it's old) 2 physical cores, 2 logical cores per core (total 4) ~2.5GHz (it can go as low as 1.8GHz, because it's on a laptop)
- RAM DDR4 16GB

As I said in #969, I think the problem is GC mid-gameplay
