### ISSUE TITLE
Bug Report: I'm Compiling the game and I got these two errors!

### ISSUE THREAD

**Issue by PointyTheUnrealProject** [FunkinCrew/Funkin#687]
source_cman/Controls.hx:411: characters 25-33 : Array<Int> has no field contains
source_cman/Replay.hx:94: characters 16-17 : Missing type declaration

And I didn't even touch these files.

**Comment by TentaRJ** [comment]
## Woah buddy!
You are receiving this message because you either:
1. Placed your entire issue in the title
2. Didn't properly use the template as specified for issues
3. Both
### Please fix this problem by editing your issue or by closing it!
### Also, this problem should be posted on the Kade-Engine repository because of `Replay.hx`.
