### ISSUE TITLE
Bug Report: Game closes itself when quickly scrolling through freeplay

### ISSUE THREAD

**Issue by OPNA2608** [FunkinCrew/Funkin#744]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

x86_64 Linux, self-built

## What version of the game are you using? Look in the bottom left corner of the main menu.

v0.2.7.1 according to the game, but I've built commit faaf064e37d5a150d8aba451d740eeb81bd2e974 with PR #412 applied.

## Please describe your issue. Provide extensive detail and images if possible.

Scrolling through the list of songs in freeplay too quickly causes the game to close itself. It's not a specific amount of total up/down movements or wrap-arounds that causes this, but rather too many changes in a short amount of time, since scrolling more slowly doesn't cause the game to quit.

https://user-images.githubusercontent.com/23431373/114307546-669f4d80-9ae0-11eb-95f6-4a000e3c6cc0.mp4

**Comment by Two-Ai** [comment]
I haven't been able to repro this exactly, but I'm pretty sure it has to do with the `NGio.logEvent()` call at https://github.com/ninjamuffin99/Funkin/blob/master/source/FreeplayState.hx#L260-L264, which causes a network request every time the song selection is changed.

It might be enough to fix this by gating the call on `#if ng` (instead of `#if !switch`), but I think it would be best to remove the logging altogether. (I can't imagine having a record of every time someone changed songs is that useful.)
