### ISSUE TITLE
Bug Report: Suicide Softlock on song fadeout

### ISSUE THREAD

**Issue by N-SPC700** [FunkinCrew/Funkin#748]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Tested with Windows (`x86_64`). 

## What version of the game are you using? Look in the bottom left corner of the main menu.

Version 0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

- Select song of choice in Free Play mode (can even be a custom song)
- Play through the song successfully until it ends
- Right as the fadeout happens, press the Retry/Suicide key. The timing is fairly strict, so it should be about the start of the fadeout and at the song's end.
- If done successfully, the player should play their death animation as usual during the fadeout, but the player is put in a glitched state. Pressing ESC to return to the song menu doesn't work, and pressing ENTER to retry the "song" (which just ended) will get the game stuck on a black screen.

Thanks to some additional testing by @OPNA2608, this bug is confirmed working on his Linux build. There the console prints statements relating to what's going on:

- During fadeout:
`source/PlayState.hx:1779: WENT BACK TO FREEPLAY??`
- When pressing R to trigger the bug:
`source/PlayState.hx:1567: RESET = True`

Those two seem to correspond to [here](https://github.com/ninjamuffin99/Funkin/blob/faaf064e37d5a150d8aba451d740eeb81bd2e974/source/PlayState.hx#L1779) and [here](https://github.com/ninjamuffin99/Funkin/blob/faaf064e37d5a150d8aba451d740eeb81bd2e974/source/PlayState.hx#L1567) respectively. I'm not a (good) coder, but it seems like the game doesn't know how to handle restarting a song that doesn't exist, or restarting outside the main gameplay areas (not the menus).

**Comment by N-SPC700** [comment]
Guess I'll add onto the first post, stating that I haven't tested this in Story Mode. It probably should work the same, but I cannot confirm if this can be triggered in Story Mode.

**Comment by vyrulow** [comment]
I am on Windows(x86_64), game version 0.2.7.1, and I was able to recreate this bug fairly consistently. I should note however that once the fade happens and you see the retry button, you can hit Enter and it will register the button press and fade away as if it was going to restart the song, but since there is no longer an active song to replay the game just sits at the black screen because it has no other instruction to fill. To add on to @N-SPC700 's suggestion, I would add some sort of gate/counter that ticks to off once the last note has been hit so that the retry button can no longer be used.
