### ISSUE TITLE
New Crash Bug

### ISSUE THREAD

**Issue by Dinobam100** [FunkinCrew/Funkin#75]
Playing Week 3 then Week 2 crashes the game for whatever reason. I haven't played any other weeks/freeplay levels before that, just went straight into Week 3 then 2.

**Comment by dinkstr** [comment]
It's being caused by these lines in PlayState.hx:

When Week 3 is started, curStage is set to "philly", but no other code changes it back once the week is over. 
https://github.com/ninjamuffin99/Funkin/blob/be5d76966ff1cab7099541071d6ed852fa8352ab/source/PlayState.hx#L152-L154

I'll try and make a pull request once I figure out how git works again.
