### ISSUE TITLE
awful menu noises

### ISSUE THREAD

**Issue by lolkittycute** [FunkinCrew/Funkin#76]
after finishing a week and going to the menu, it'll start making really loud beat noises over and over really fast until I load a song. It seems to do this randomly so I'm not sure what triggers it

**Comment by ElijahZAwesome** [comment]
This happens because the vocal track (and I think the instrumental(?)) are set to loop after finishing, and dont actually stop when the song is finished, they only tell the game to transition to the main menu again. 

Make the tracks not loop @ninjamuffin99 xD ~~and maybe cache the instrumental in generateSong() too so the game doesn't hitch once you start hitting notes?~~
