### ISSUE TITLE
Bug Report: 2 issues

### ISSUE THREAD

**Issue by DamianBossPL** [FunkinCrew/Funkin#768]
## First Issue
Each 3rd song from every week on the Story Menu is missing and single song weeks like Tutorial are Missing.
![image](https://user-images.githubusercontent.com/77542487/115062545-5f15e500-9ee2-11eb-8fe0-287c2f2b0a41.png)
![image](https://user-images.githubusercontent.com/77542487/115062607-6fc65b00-9ee2-11eb-9c7a-0a407c07a042.png)

## Second Issue
Latest Version but still says outdated
![image](https://user-images.githubusercontent.com/77542487/115062965-d9df0000-9ee2-11eb-8e89-6bad77bca533.png)

# Contents
![image](https://user-images.githubusercontent.com/77542487/115063648-bd8f9300-9ee3-11eb-9dc3-af5b81d41838.png)

I really need the help!

# Note
This is a fresh copy of the game from https://github.com/ninjamuffin99/Funkin

**Comment by trayfellow** [comment]
i solved the first problem in another issue yesterday so make sure the versions of your libraries are like this :
![image](https://user-images.githubusercontent.com/48515908/115098484-81e3e000-9f5a-11eb-9913-5dcc64f34b91.png)

in order to downgrade to a different version of a library, you can do something like 'haxelib install flixel 4.8.1' then do 'haxelib set flixel 4.8.1' and then 'haxelib remove flixel 4.9.0'

also this is how i solved the second issue i go to playstate.hx and at this line of code 

![image](https://user-images.githubusercontent.com/48515908/115098692-983e6b80-9f5b-11eb-8e90-2a363e00aa18.png)

i replace the 'FlxG.switchState(new OutdatedSubState());
					trace('OLD VERSION!');
					trace('old ver');
					trace(version.trim());
					trace('cur ver');
					trace(NGio.GAME_VER_NUMS.trim());'

with  'FlxG.switchState(new MainMenuState());' since i cant code 

![image](https://user-images.githubusercontent.com/48515908/115098723-c58b1980-9f5b-11eb-958a-e4dcd71f2a86.png)

hope it helps!

**Comment by DamianBossPL** [comment]
I solved the first problem, but where is that line? I tried using F3 to find it, but nothing. Do you have the latest version:
v0.2.7.1
![image](https://user-images.githubusercontent.com/77542487/115103403-7cca6500-9f49-11eb-83a4-31c94f3c2bf6.png)

**Comment by DamianBossPL** [comment]
nvm it was in TitleState.hx

**Comment by DamianBossPL** [comment]
It worked!! Thanks!
