### ISSUE TITLE
Question: What is "SNIFF"?

### ISSUE THREAD

**Issue by jbmagination** [FunkinCrew/Funkin#883]
## What is your question?

Hey there! In the attempt to archive the Newgrounds version of 0.2.8, I decided to take a peek at the .json files for Guns (just now), and found `"generatedBy":"SNIFF ver.6"` at the very end of the .json file.

The only theory I have: I wanna say this is the level editor for the full game mentioned in the Kickstarter trailer, but the "ver.6" is throwing me off on that trail.

Any official word, even just a "no comment", would be excellent.

**Comment by ninjamuffin99** [comment]
SNIFF is a tool that @PrincessMtH made, she uses it for charts instead of the in-game chart editor. Basic rundown is that it actually lets you chart it in FL Studio! Useful for a charting alternative, I think she might toss it out there on github at some point.

MtH recharted a good few songs, and charted some of the new ones, SNIFF tosses that into the song JSONs I suppose!

**Comment by PrincessMtH** [comment]
yeee ima release it eventually but rn it's got some bugs and is missing one of the new week7 features. also not the prettiest to look at cuz its all command line. but it'll come out eventually! also SNIFF stands for SiIva Note Importer For FNF cuz i originally made it for siivagunner team lol

**Comment by PrincessMtH** [comment]
it out now btw https://github.com/PrincessMtH/SNIFF

**Comment by jbmagination** [comment]
very nice
