### ISSUE TITLE
Bug Report: You Can Miss notes during the start of the week 6 thorns cutscene.

### ISSUE THREAD

**Issue by alfunker153** [FunkinCrew/Funkin#911]
I am using the Newgrounds preview of FNF. I was playing week 6 and I noticed you can press keys and they will count toward your score at the start of the thorns cutscene. This is a minor bug but I hope it gets fixed.

.

**Comment by vyrulow** [comment]
I am on Windows 64-bit, I've tried both on the HTML5 and the downloaded version and it seems you can do this on basically any of the openers. It seems to me like the key listeners are active just a bit too early, this is easy to see because of the arrow key placeholders being in the background while the text is still showing up. I think the fix here would be to delay the listeners activating until after all the initial text introductions are finished. I have also checked out a couple of the mods and those that give the ability to change the input type do not have this problem so it definitely lies within the realm of the "old input" scheme.
